/**
 * Client Type Definitions
 *
 * Type definitions for Client entities matching the backend schema
 * Clients are advertisers who book sites
 */

/**
 * Main Client Interface
 *
 * Represents an advertising client/customer
 * Field names match backend schema exactly
 * @property id - Unique identifier (UUID)
 * @property clientNo - Unique client number (e.g., "CLI-001")
 * @property name - Business or individual name
 * @property contactPerson - Contact person name
 * @property email - Email address
 * @property phone - Phone number
 * @property address - Physical address
 * @property gstNumber - GST registration number (15 chars, alphanumeric)
 * @property notes - Additional notes
 * @property createdAt - Creation timestamp (ISO string)
 * @property updatedAt - Last update timestamp (ISO string)
 */
export interface Client {
  id: string;
  clientNo: string;
  name: string;
  contactPerson?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  gstNumber?: string | null;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create Client Request
 *
 * Data required to create a new client
 * Omits id, clientNo, and timestamps (auto-generated by backend)
 */
export interface CreateClientRequest {
  name: string;
  contactPerson?: string;
  email?: string;
  phone?: string;
  address?: string;
  gstNumber?: string;
  notes?: string;
}

/**
 * Update Client Request
 *
 * Data for updating an existing client
 * All fields are optional except id
 */
export interface UpdateClientRequest {
  id: string;
  name?: string;
  contactPerson?: string;
  email?: string;
  phone?: string;
  address?: string;
  gstNumber?: string;
  notes?: string;
}

/**
 * Client Filters
 *
 * Filter criteria for querying clients
 */
export interface ClientFilters {
  searchTerm?: string;
}

/**
 * Client Search Result
 *
 * Paginated response for client queries
 */
export interface ClientSearchResult {
  clients: Client[];
  total: number;
  page: number;
  limit: number;
}

/**
 * Client with Statistics
 *
 * Extended client info with booking and revenue stats
 * Used in client detail views
 */
export interface ClientWithStats extends Client {
  totalBookings: number;
  activeBookings: number;
  totalRevenue: number;
}

/**
 * GST Number Validation Pattern
 *
 * Format: 15 characters
 * Pattern: 2 digits (state) + 10 chars (PAN) + 1 char (entity) + Z + 1 char
 * Example: 29ABCDE1234F1Z5
 */
export const GST_NUMBER_PATTERN = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;

/**
 * Helper function to validate GST number format
 */
export const isValidGSTNumber = (gstNo: string): boolean => {
  return GST_NUMBER_PATTERN.test(gstNo);
};
