/**
 * Site Type Definitions
 *
 * Type definitions for Site entities matching the backend schema
 * Sites represent physical billboard/unipole locations
 */

/**
 * Site Type - Constraint for advertising structure type
 */
export type SiteType = 'unipole' | 'hoarding';

/**
 * Main Site Interface
 *
 * Represents a physical advertising site (billboard/unipole)
 * @property id - Unique identifier (UUID)
 * @property siteNo - Unique site number (alphanumeric, e.g., "12B")
 * @property location - Descriptive location (e.g., "DPS Circle")
 * @property type - Structure type (unipole or hoarding)
 * @property size - Dimensions as string (e.g., "20 * 10")
 * @property remarks - Optional notes about the site
 * @property createdAt - Creation timestamp (ISO string)
 * @property updatedAt - Last update timestamp (ISO string)
 */
export interface Site {
  id: string;
  siteNo: string;
  location: string;
  type: SiteType;
  size: string;
  remarks?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Create Site Request
 *
 * Data required to create a new site
 * Omits id and timestamps (auto-generated by backend)
 */
export interface CreateSiteRequest {
  siteNo: string;
  location: string;
  type: SiteType;
  size: string;
  remarks?: string;
}

/**
 * Update Site Request
 *
 * Data for updating an existing site
 * All fields are optional except id
 */
export interface UpdateSiteRequest {
  id: string;
  siteNo?: string;
  location?: string;
  type?: SiteType;
  size?: string;
  remarks?: string;
}

/**
 * Site Filters
 *
 * Filter criteria for querying sites
 */
export interface SiteFilters {
  type?: SiteType;
  location?: string;
  searchTerm?: string;
}

/**
 * Site Search Result
 *
 * Paginated response for site queries
 */
export interface SiteSearchResult {
  sites: Site[];
  total: number;
  page: number;
  limit: number;
}

/**
 * Site Current Status
 *
 * Extended site info including current occupancy status
 * Used in dashboard and site lists to show active client
 */
export interface SiteCurrentStatus {
  // Site information
  siteId: string;
  siteNo: string;
  location: string;
  type: SiteType;
  size: string;
  remarks?: string;

  // Current occupancy information
  currentClientId?: string;
  currentClientName?: string;
  currentActivityId?: string;
  activeFromDate?: string;
  activeToDate?: string;
}

/**
 * Site Status - Computed from current activity
 */
export type SiteStatus = 'active' | 'available';

/**
 * Helper function to determine site status
 */
export const getSiteStatus = (site: SiteCurrentStatus): SiteStatus => {
  return site.currentClientId ? 'active' : 'available';
};
